// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"go-digilib/auth"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(ctx context.Context, req *auth.LoginRequest) (auth.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 auth.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) (auth.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) auth.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(auth.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.LoginRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.LoginRequest
func (_e *MockService_Expecter) Login(ctx any, req any) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockService_Login_Call) Run(run func(ctx context.Context, req *auth.LoginRequest)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(user auth.User, err error) *MockService_Login_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(ctx context.Context, req *auth.LoginRequest) (auth.User, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockService
func (_mock *MockService) Register(ctx context.Context, req *auth.RegisterRequest) (auth.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 auth.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RegisterRequest) (auth.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RegisterRequest) auth.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(auth.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.RegisterRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.RegisterRequest
func (_e *MockService_Expecter) Register(ctx any, req any) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, req *auth.RegisterRequest)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Register_Call) Return(user auth.User, err error) *MockService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(ctx context.Context, req *auth.RegisterRequest) (auth.User, error)) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}
