// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package settings

import (
	"context"
	"go-digilib/settings"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, settingReq *settings.SettingRequest) (settings.Setting, error) {
	ret := _mock.Called(ctx, settingReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 settings.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *settings.SettingRequest) (settings.Setting, error)); ok {
		return returnFunc(ctx, settingReq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *settings.SettingRequest) settings.Setting); ok {
		r0 = returnFunc(ctx, settingReq)
	} else {
		r0 = ret.Get(0).(settings.Setting)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *settings.SettingRequest) error); ok {
		r1 = returnFunc(ctx, settingReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - settingReq *settings.SettingRequest
func (_e *MockService_Expecter) Create(ctx any, settingReq any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, settingReq)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, settingReq *settings.SettingRequest)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *settings.SettingRequest
		if args[1] != nil {
			arg1 = args[1].(*settings.SettingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(setting settings.Setting, err error) *MockService_Create_Call {
	_c.Call.Return(setting, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, settingReq *settings.SettingRequest) (settings.Setting, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockService_Expecter) Delete(ctx any, id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockService
func (_mock *MockService) GetAll(ctx context.Context) ([]settings.Setting, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []settings.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]settings.Setting, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []settings.Setting); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]settings.Setting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetAll(ctx any) *MockService_GetAll_Call {
	return &MockService_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockService_GetAll_Call) Run(run func(ctx context.Context)) *MockService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetAll_Call) Return(settings1 []settings.Setting, err error) *MockService_GetAll_Call {
	_c.Call.Return(settings1, err)
	return _c
}

func (_c *MockService_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]settings.Setting, error)) *MockService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(ctx context.Context, id uint) (settings.Setting, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 settings.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (settings.Setting, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) settings.Setting); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(settings.Setting)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockService_Expecter) GetByID(ctx any, id any) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(setting settings.Setting, err error) *MockService_GetByID_Call {
	_c.Call.Return(setting, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (settings.Setting, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKey provides a mock function for the type MockService
func (_mock *MockService) GetByKey(ctx context.Context, key string) (settings.Setting, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 settings.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (settings.Setting, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) settings.Setting); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(settings.Setting)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockService_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockService_Expecter) GetByKey(ctx any, key any) *MockService_GetByKey_Call {
	return &MockService_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, key)}
}

func (_c *MockService_GetByKey_Call) Run(run func(ctx context.Context, key string)) *MockService_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByKey_Call) Return(setting settings.Setting, err error) *MockService_GetByKey_Call {
	_c.Call.Return(setting, err)
	return _c
}

func (_c *MockService_GetByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (settings.Setting, error)) *MockService_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, settingReq *settings.SettingRequest, id uint) (settings.Setting, error) {
	ret := _mock.Called(ctx, settingReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 settings.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *settings.SettingRequest, uint) (settings.Setting, error)); ok {
		return returnFunc(ctx, settingReq, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *settings.SettingRequest, uint) settings.Setting); ok {
		r0 = returnFunc(ctx, settingReq, id)
	} else {
		r0 = ret.Get(0).(settings.Setting)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *settings.SettingRequest, uint) error); ok {
		r1 = returnFunc(ctx, settingReq, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - settingReq *settings.SettingRequest
//   - id uint
func (_e *MockService_Expecter) Update(ctx any, settingReq any, id any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, settingReq, id)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, settingReq *settings.SettingRequest, id uint)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *settings.SettingRequest
		if args[1] != nil {
			arg1 = args[1].(*settings.SettingRequest)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(setting settings.Setting, err error) *MockService_Update_Call {
	_c.Call.Return(setting, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, settingReq *settings.SettingRequest, id uint) (settings.Setting, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
