// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users

import (
	"context"
	"go-digilib/users"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function for the type MockService
func (_mock *MockService) GetProfile(ctx context.Context, userID uint) (users.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 users.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (users.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) users.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(users.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockService_Expecter) GetProfile(ctx any, userID any) *MockService_GetProfile_Call {
	return &MockService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockService_GetProfile_Call) Run(run func(ctx context.Context, userID uint)) *MockService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetProfile_Call) Return(user users.User, err error) *MockService_GetProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_GetProfile_Call) RunAndReturn(run func(ctx context.Context, userID uint) (users.User, error)) *MockService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, editReq *users.EditProfileRequest, id uint) (users.User, error) {
	ret := _mock.Called(ctx, editReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 users.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *users.EditProfileRequest, uint) (users.User, error)); ok {
		return returnFunc(ctx, editReq, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *users.EditProfileRequest, uint) users.User); ok {
		r0 = returnFunc(ctx, editReq, id)
	} else {
		r0 = ret.Get(0).(users.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *users.EditProfileRequest, uint) error); ok {
		r1 = returnFunc(ctx, editReq, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - editReq *users.EditProfileRequest
//   - id uint
func (_e *MockService_Expecter) Update(ctx any, editReq any, id any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, editReq, id)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, editReq *users.EditProfileRequest, id uint)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *users.EditProfileRequest
		if args[1] != nil {
			arg1 = args[1].(*users.EditProfileRequest)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(user users.User, err error) *MockService_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, editReq *users.EditProfileRequest, id uint) (users.User, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
