// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package books

import (
	"context"
	"go-digilib/books"
	"go-digilib/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, bookReq *books.BookRequest) (books.Book, error) {
	ret := _mock.Called(ctx, bookReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 books.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *books.BookRequest) (books.Book, error)); ok {
		return returnFunc(ctx, bookReq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *books.BookRequest) books.Book); ok {
		r0 = returnFunc(ctx, bookReq)
	} else {
		r0 = ret.Get(0).(books.Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *books.BookRequest) error); ok {
		r1 = returnFunc(ctx, bookReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - bookReq *books.BookRequest
func (_e *MockService_Expecter) Create(ctx any, bookReq any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, bookReq)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, bookReq *books.BookRequest)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *books.BookRequest
		if args[1] != nil {
			arg1 = args[1].(*books.BookRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(book books.Book, err error) *MockService_Create_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, bookReq *books.BookRequest) (books.Book, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockService_Expecter) Delete(ctx any, id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockService
func (_mock *MockService) GetAll(ctx context.Context, pagination utils.Pagination) (utils.Pagination, error) {
	ret := _mock.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 utils.Pagination
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, utils.Pagination) (utils.Pagination, error)); ok {
		return returnFunc(ctx, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, utils.Pagination) utils.Pagination); ok {
		r0 = returnFunc(ctx, pagination)
	} else {
		r0 = ret.Get(0).(utils.Pagination)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, utils.Pagination) error); ok {
		r1 = returnFunc(ctx, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination utils.Pagination
func (_e *MockService_Expecter) GetAll(ctx any, pagination any) *MockService_GetAll_Call {
	return &MockService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, pagination)}
}

func (_c *MockService_GetAll_Call) Run(run func(ctx context.Context, pagination utils.Pagination)) *MockService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 utils.Pagination
		if args[1] != nil {
			arg1 = args[1].(utils.Pagination)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetAll_Call) Return(pagination1 utils.Pagination, err error) *MockService_GetAll_Call {
	_c.Call.Return(pagination1, err)
	return _c
}

func (_c *MockService_GetAll_Call) RunAndReturn(run func(ctx context.Context, pagination utils.Pagination) (utils.Pagination, error)) *MockService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCategory provides a mock function for the type MockService
func (_mock *MockService) GetByCategory(ctx context.Context, pagination utils.Pagination, categoryId uint) (utils.Pagination, error) {
	ret := _mock.Called(ctx, pagination, categoryId)

	if len(ret) == 0 {
		panic("no return value specified for GetByCategory")
	}

	var r0 utils.Pagination
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, utils.Pagination, uint) (utils.Pagination, error)); ok {
		return returnFunc(ctx, pagination, categoryId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, utils.Pagination, uint) utils.Pagination); ok {
		r0 = returnFunc(ctx, pagination, categoryId)
	} else {
		r0 = ret.Get(0).(utils.Pagination)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, utils.Pagination, uint) error); ok {
		r1 = returnFunc(ctx, pagination, categoryId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCategory'
type MockService_GetByCategory_Call struct {
	*mock.Call
}

// GetByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination utils.Pagination
//   - categoryId uint
func (_e *MockService_Expecter) GetByCategory(ctx any, pagination any, categoryId any) *MockService_GetByCategory_Call {
	return &MockService_GetByCategory_Call{Call: _e.mock.On("GetByCategory", ctx, pagination, categoryId)}
}

func (_c *MockService_GetByCategory_Call) Run(run func(ctx context.Context, pagination utils.Pagination, categoryId uint)) *MockService_GetByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 utils.Pagination
		if args[1] != nil {
			arg1 = args[1].(utils.Pagination)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetByCategory_Call) Return(pagination1 utils.Pagination, err error) *MockService_GetByCategory_Call {
	_c.Call.Return(pagination1, err)
	return _c
}

func (_c *MockService_GetByCategory_Call) RunAndReturn(run func(ctx context.Context, pagination utils.Pagination, categoryId uint) (utils.Pagination, error)) *MockService_GetByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(ctx context.Context, id uint) (books.Book, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 books.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (books.Book, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) books.Book); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(books.Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockService_Expecter) GetByID(ctx any, id any) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(book books.Book, err error) *MockService_GetByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (books.Book, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, bookReq *books.BookRequest, id uint) (books.Book, error) {
	ret := _mock.Called(ctx, bookReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 books.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *books.BookRequest, uint) (books.Book, error)); ok {
		return returnFunc(ctx, bookReq, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *books.BookRequest, uint) books.Book); ok {
		r0 = returnFunc(ctx, bookReq, id)
	} else {
		r0 = ret.Get(0).(books.Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *books.BookRequest, uint) error); ok {
		r1 = returnFunc(ctx, bookReq, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - bookReq *books.BookRequest
//   - id uint
func (_e *MockService_Expecter) Update(ctx any, bookReq any, id any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, bookReq, id)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, bookReq *books.BookRequest, id uint)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *books.BookRequest
		if args[1] != nil {
			arg1 = args[1].(*books.BookRequest)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(book books.Book, err error) *MockService_Update_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, bookReq *books.BookRequest, id uint) (books.Book, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
