// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package carts

import (
	"context"
	"go-digilib/carts"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, cartReq *carts.CartRequest) (carts.Cart, error) {
	ret := _mock.Called(ctx, cartReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 carts.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *carts.CartRequest) (carts.Cart, error)); ok {
		return returnFunc(ctx, cartReq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *carts.CartRequest) carts.Cart); ok {
		r0 = returnFunc(ctx, cartReq)
	} else {
		r0 = ret.Get(0).(carts.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *carts.CartRequest) error); ok {
		r1 = returnFunc(ctx, cartReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cartReq *carts.CartRequest
func (_e *MockService_Expecter) Create(ctx any, cartReq any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, cartReq)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, cartReq *carts.CartRequest)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *carts.CartRequest
		if args[1] != nil {
			arg1 = args[1].(*carts.CartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(cart carts.Cart, err error) *MockService_Create_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, cartReq *carts.CartRequest) (carts.Cart, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockService_Expecter) Delete(ctx any, id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(ctx context.Context, id uint) (carts.Cart, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 carts.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (carts.Cart, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) carts.Cart); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(carts.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockService_Expecter) GetByID(ctx any, id any) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(cart carts.Cart, err error) *MockService_GetByID_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (carts.Cart, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockService
func (_mock *MockService) GetByUser(ctx context.Context, userId uint) ([]carts.Cart, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []carts.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]carts.Cart, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []carts.Cart); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]carts.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockService_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint
func (_e *MockService_Expecter) GetByUser(ctx any, userId any) *MockService_GetByUser_Call {
	return &MockService_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userId)}
}

func (_c *MockService_GetByUser_Call) Run(run func(ctx context.Context, userId uint)) *MockService_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByUser_Call) Return(carts1 []carts.Cart, err error) *MockService_GetByUser_Call {
	_c.Call.Return(carts1, err)
	return _c
}

func (_c *MockService_GetByUser_Call) RunAndReturn(run func(ctx context.Context, userId uint) ([]carts.Cart, error)) *MockService_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, cartReq *carts.CartRequest, id uint) (carts.Cart, error) {
	ret := _mock.Called(ctx, cartReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 carts.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *carts.CartRequest, uint) (carts.Cart, error)); ok {
		return returnFunc(ctx, cartReq, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *carts.CartRequest, uint) carts.Cart); ok {
		r0 = returnFunc(ctx, cartReq, id)
	} else {
		r0 = ret.Get(0).(carts.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *carts.CartRequest, uint) error); ok {
		r1 = returnFunc(ctx, cartReq, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cartReq *carts.CartRequest
//   - id uint
func (_e *MockService_Expecter) Update(ctx any, cartReq any, id any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, cartReq, id)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, cartReq *carts.CartRequest, id uint)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *carts.CartRequest
		if args[1] != nil {
			arg1 = args[1].(*carts.CartRequest)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(cart carts.Cart, err error) *MockService_Update_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, cartReq *carts.CartRequest, id uint) (carts.Cart, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
